export const SET_TOP_RATED_MOVIES: string = "SET_TOP_RATED_MOVIES"
export const SET_UPCOMING_MOVIES: string = "SET_UPCOMING_MOVIES"

export const SET_TOP_RATED_MOVIES_ERROR: string = "SET_TOP_RATED_MOVIES_ERROR"
export const SET_UPCOMING_MOVIES_ERROR: string = "SET_UPCOMING_MOVIES_ERROR"
