export const SET_TOP_RATED_MOVIES: string = "SET_TOP_RATED_MOVIES"
export const SET_UPCOMING_MOVIES: string = "SET_UPCOMING_MOVIES"

export const SET_FOUND_MOVIES: string = "SET_FOUND_MOVIES"
export const ADD_MORE_FOUND_MOVIES: string = "ADD_MORE_FOUND_MOVIES"
